### ISSUE TITLE
How were sentinel images preprocessed in Worldstrat dataset?

### ISSUE THREAD

**Issue by xavierxav** [worldstrat/worldstrat#19]
Hello,

A lot of sentinel images of the dataset have really low brightness, and images with clouds seem to have too high contrast between clouds and land. Here I uploaded 12 images of Amnesty POI-10-1-2, first two rows without any processing from my part, then with simple normalization (img - img_min) / (img_max - img_min) which makes visible only images without clouds, and then last two rows when I force mean and std to standard values which gives visibility to images with low cloud cover.

Did you use a special preprocessing on your sentinel images that could explain this ?

![image](https://github.com/user-attachments/assets/744724d8-9b1b-41bd-aa8a-69f370c103c4)
![image](https://github.com/user-attachments/assets/ac5ae237-675c-43ab-a5e5-4dcf55b8c3c7)
![image](https://github.com/user-attachments/assets/f11da8a7-914c-493f-8ff0-6abebbc39d02)

**Comment by ivanorsolic** [comment]
Hey @xavierxav, 

This behaviour is normal. Sometimes there are highly reflective things in the scene, like clouds, or sometimes even a really shiny piece of metal reflecting sunlight directly into the satellite sensor. This causes those pixel locations to have huge values, since satellite sensors aren't really bound by a range like an 8-bit RGB image would be. They can be 10-bit, 12-bit or even more.

If you just do a naive normalization then (e.g. subtracting the min, and dividing by the max-min range), a few of those huge values will squish the vast majority of the other values, which are in normal range, close to zero. This will make the image dark, except for those highly reflective parts.

For that reason, you should always refer to the imagery provider / satellite manufacturer for what should be a reasonable range of values for a specific sensor, and a specific band. Then you should discard any values above a certain threshold (often suggested by the provider), which is considered a reasonable max value. The provider often offers several tiers of data, from the least processed/most raw data, often called radiance, to fully processed and analysis-ready data.

**In our dataset, we opted to have the least amount of preprocessing done in the dataset itself, which in turn means the data isn't analysis ready if it's just loaded from the disk. It needs to be preprocessed. We preprocess the [data before training](https://github.com/worldstrat/worldstrat/blob/main/src/datasets.py#L1749).** 

We recommend running the _Data exploration_ notebook if you want to play around with the code, or preview the images.

That being said, I'm sure you're not the first person to wonder about this, so we will make a notebook with a guide on the data lifecycle, from the photons hitting the satellite sensor to analysis ready imagery.

For now, here's a brief overview:

- The raw energy that the satellite observes and measures at the sensor is called **radiance**.
- Unprocessed radiance includes any atmospheric distrubance, molecular or Rayleigh diffusion.
- These values are often called Digital Number (DN) values.
- If we want to do any sort of analysis on these raw images, or even preview them in true color, we need to do a lot of processing.
- Besides atmospheric corrections, this processing includes other corrections, like trimming high values outside the expected range, eliminating issues like the ones you faced.

![](https://github.com/user-attachments/assets/05f6231e-2496-4e4e-9d77-a37d7806f9af)
Source: https://www.un-spider.org/node/10958

Sentinel-2 has three levels of data processing:
- [Level-0 data ](https://sentinels.copernicus.eu/en/web/sentinel/technical-guides/sentinel-2-msi/level-0-algorithms-products)is the raw data that the satellite processes in real-time, on-board, to ensure data integrity.
- Level-1 (A/B/C). [Level-1C](https://sentinels.copernicus.eu/en/web/sentinel/technical-guides/sentinel-2-msi/level-1c-algorithms-products) is Top-of-Atmosphere (TOA) data, allowing you to perform your own atmospheric correction.
- [Level-2A](https://sentinels.copernicus.eu/en/web/sentinel/technical-guides/sentinel-2-msi/level-2a-algorithms-products) is Bottom-of-Atmosphere (BOA) data, with atmospheric correction already applied.

In our dataset, for Sentinel-2 imagery, we offer Level-1C and Level-2A processing. [Here are the typical ranges for the Sentinel Level-2A](https://documentation.dataspace.copernicus.eu/APIs/SentinelHub/Data/S2L2A.html#units) you were experimenting with.

For SPOT, we offer the raw data, and orthorectified, pan-sharpened images ready for analysis.
[Here are some expected values for SPOT6/7](https://earth.esa.int/eogateway/documents/20142/37627/SPOT-6-7-imagery-user-guide.pdf?page=33).

This is just the tip of the iceberg when it comes to satellite imagery normalisation and pre-processing. It's both a fascinating and a complicated topic. We'll try to put out a notebook soon that can help the users of this dataset understand at least the dataset-specific preprocessing and corrections.

If you're interested in learning more, the ESA regularly holds training courses on remote sensing, and atmospheric and other corrections are a key part of the trainings. [Here is a great example.](https://eo4society.esa.int/wp-content/uploads/2021/02/D2T1b_LTC2015_Gastellu-Etchegorry.pdf)

**Comment by jucor** [comment]
@xavierxav Thanks for the question, and thanks @ivanorsolic for the answer :) Please let us know if this is clear, so we can close this issue.
(as you can see, we're not quite on top of the issue tracker at the moment 😅 , but I have hope, we'll get there!)

**Comment by xavierxav** [comment]
Hey @ivanorsolic and @jucor ,

Thank you @ivanorsolic  for your clear and helpful reply! A notebook on the data lifecycle would be great indeed.
